export const ROUTES = {
  TABS: 'Tabs',
  INITIALAUTH: 'InitialAuthScreen',
  // HOME: 'Home',
  HOMESCREEN: 'HomeScreen',
  LOGIN: 'LoginScreen',
  GETSTARTED: 'GetStarted',
  REGISTER: 'RegisterScreen',
  CREATEUSERPROFILE: 'CreateUserUploadProfie',
  AUTHSCREEN: 'Authscreen',
  SETTING: 'Setting',
  PROFILE: 'Profile',
  PROFILESCREEN: 'ProfileScreen',
  EDITPROFILE: 'EditProfile',
  FOLLOWIUP: 'FollowUp',
  PROFILEUPLOADS: 'ProfileUploads',

  CHARTS: 'Charts',
  CREATESUPPORTPLAN: 'CreateSupportPlan',
  DISCOVERSEARCHSCREEN: 'discoverSearchScreen',
  UPLOAD: 'Upload',
  CLASHARENA: 'ClashArena',
  TOPTALENTS: 'TopTalents',
  UPLOADPOST: 'UploadPost',
  DISCOVERSCREEN: 'DiscoverScreen',
  NOTIFICATIONSCREEN: 'NotificationScreen',
  MESSAGESDASHBOARD: 'MessagesDashboard',
  UPLOADRECORD: 'UploadRecord',
  STARTCLASH: 'StartClash',
  FEED: 'Feed',
  HOME: 'Home',
  STORE: 'Store',
  RESERVE: 'Reserve',
};
